# Generated by Django 3.2.3 on 2021-05-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pub_date',
            new_name='created',
        ),
    ]
